# Default test configuration for probability analysis

# Model Configuration
model:
  name: "gpt2"  # Model to test (can be local path or HuggingFace model name)
  device: "auto"  # Device to run on (auto, cuda, cpu)
  
# Generation Configuration
generation:
  # Generation parameters
  max_new_tokens: 50  # Maximum number of new tokens to generate
  num_samples: 100  # Number of generation samples for probability analysis
  temperature: 1.0  # Sampling temperature
  top_p: 0.9  # Nucleus sampling parameter
  top_k: 50  # Top-k sampling parameter
  do_sample: true  # Whether to use sampling
  pad_token_id: null  # Padding token ID (null for auto-detection)
  
  # Prompt configuration
  prompt: "The quick brown fox"  # Default prompt for testing
  prompt_file: null  # Optional: path to file containing prompts (one per line)
  
# Analysis Configuration
analysis:
  # Probability analysis settings
  save_logits: true  # Whether to save raw logits for each timestep
  save_probabilities: true  # Whether to save probability distributions
  top_k_probs: 10  # Number of top-k probabilities to save for each timestep
  
  # Output settings
  output_dir: "test_results"  # Directory to save results
  save_format: "json"  # Output format (json, pickle, both)
  save_visualizations: true  # Whether to generate visualization plots
  
# Visualization Configuration
visualization:
  # Plot settings
  plot_top_k: 5  # Number of top tokens to show in probability plots
  plot_width: 12  # Plot width in inches
  plot_height: 8  # Plot height in inches
  dpi: 300  # Plot resolution
  
  # Color settings
  colormap: "viridis"  # Colormap for heatmaps
  colorbar: true  # Whether to show colorbar
  
# Experiment Configuration
experiment:
  name: "default_test"  # Name of the experiment
  description: "Default probability analysis test"  # Description
  seed: 42  # Random seed for reproducibility
  
# Environment Configuration
env:
  hf_token_env: "RUNPOD_HF_TOKEN"  # Environment variable for HuggingFace token
  wandb_token_env: "RUNPOD_WANDB_TOKEN"  # Environment variable for Weights & Biases token
  wandb_project: "sequence-aware-testing"  # Weights & Biases project name
  wandb_name: null  # Weights & Biases run name (null for auto-generated)
